# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62be3aa51bb348ad4acf9bfa17a97f8d43bbcc4f61d1324af0c26dc997a64e03d8e445cb4cc12b125ef0691cf658c5e56a52583530e2b50652299d0c35b54aec

test:
  secret_key_base: 7a505916120472b23af8bec54f682fb09e8aaddea587085d5f551b3d9e871365c404ca394641360d1be0eee3d596fb3caa29c3cd3cdec0622df751b01338a0b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
